server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:ta;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true

api:
  student-question-history:
    base-url: /api/v1/history
  exercise:
    base-url: /api/v1/exercise
  subject:
    base-url: /api/v1/subject
  topic:
    base-url: /api/v1/topic
  mastery:
    base-url: /api/v1/mastery
    submission: /submission